name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., v1.0.0, latest)'
        required: true
        default: 'latest'
      dockerfile:
        description: 'Dockerfile to use'
        required: true
        type: choice
        options:
          - docker/local.dockerfile
          - docker/serverless.dockerfile
        default: docker/local.dockerfile

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
          - runner: macos-latest
            platform: linux/arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install colima docker
          colima start --arch aarch64 --vm-type=vz --vz-rosetta --cpu 4 --memory 8
          
          # Wait for Docker daemon
          max_attempts=30
          attempt=0
          while ! docker info > /dev/null 2>&1; do
            if [ $attempt -eq $max_attempts ]; then
              echo "Docker daemon failed to start"
              colima status
              exit 1
            fi
            echo "Waiting for Docker daemon... (attempt $((attempt+1))/$max_attempts)"
            sleep 2
            attempt=$((attempt+1))
          done
          echo "Docker daemon is ready!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.tag }}
            type=raw,value=${{ github.event.inputs.tag }}-{{sha}}
            type=sha,prefix={{branch}}-,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ github.event.inputs.tag }}
          provenance: false

      - name: Clean up (macOS)
        if: always() && runner.os == 'macOS'
        run: |
          colima stop || true